# Generated by Django 4.2.2 on 2023-06-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
