# Generated by Django 4.2.2 on 2023-06-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='json',
            field=models.JSONField(null=True),
        ),
    ]
