# Generated by Django 4.2.2 on 2023-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_students_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='friends',
            field=models.ManyToManyField(to='shop.students'),
        ),
    ]
