# Generated by Django 3.2.19 on 2023-06-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20230615_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('ComputerRelated', 'ComputerRelated'), ('PlatformRelated', 'PlatformRelated'), ('InternetRelated', 'InternetRelated'), ('userRelated', 'userRelated')], default='ComputerRelated', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(blank=True, default='', max_length=50)),
                ('motivation_rating', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
