# Generated by Django 3.2.19 on 2023-06-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('ComputerRelated', 'ComputerRelated'), ('PlatformRelated', 'PlatformRelated'), ('InternetRelated', 'InternetRelated'), ('userRelated', 'userRelated')], default='ComputerRelated', max_length=30)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
